version: '3.8'
services:
  db:
    container_name: TheDentorDatabase
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES="thedentor","thedentor-test"
    ports:
      - '5432:5432'
    volumes:
      - ./apps/server/scripts:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
